# Generated by Django 3.2.21 on 2023-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Landing',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Takeoff',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='Taxi',
            field=models.JSONField(default=['0'], null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='lastInstruction',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
    ]
