# Generated by Django 3.2.21 on 2023-09-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aircraft_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
    ]
