# Generated by Django 3.2.21 on 2023-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_aircraft_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icao',
            field=models.CharField(default='IRFD', max_length=4),
        ),
    ]
