# Generated by Django 3.2.21 on 2023-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room_icao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='Incoming',
            field=models.BooleanField(default=True),
        ),
    ]
