# Generated by Django 3.2.21 on 2023-09-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aircraft_incoming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='Landing',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='Takeoff',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Add_Info',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='AircraftType',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Altitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Arrival',
            field=models.CharField(default=' ', max_length=4),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Departure',
            field=models.CharField(default=' ', max_length=4),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Gate',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Info',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Runway',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='Squawk',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
